# Generated by data-raw/generate-chk.R -- do not edit by hand.

#' @param all.missing Passed to the backing `check_*()` function as `all.missing`.
#' @param any.missing Passed to the backing `check_*()` function as `any.missing`.
#' @param class.ok If `FALSE` (the default), `x` must not carry a `class` attribute.
#' @param dim.ok If `FALSE` (the default), `x` must not carry a `dim` attribute.
#' @param finite Passed to the backing `check_*()` function as `finite`.
#' @param fixed Passed to the backing `check_*()` function as `fixed`.
#' @param ignore.case Passed to the backing `check_*()` function as `ignore.case`.
#' @param len Passed to the backing `check_*()` function as `len`.
#' @param lower Passed to the backing `check_*()` function as `lower`.
#' @param max.chars Passed to the backing `check_*()` function as `max.chars`.
#' @param max.len Passed to the backing `check_*()` function as `max.len`.
#' @param min.chars Passed to the backing `check_*()` function as `min.chars`.
#' @param min.len Passed to the backing `check_*()` function as `min.len`.
#' @param n.chars Passed to the backing `check_*()` function as `n.chars`.
#' @param na.ok Passed to the backing `check_*()` function as `na.ok`.
#' @param names Passed to the backing `check_*()` function as `names`.
#' @param null.ok Passed to the backing `check_*()` function as `null.ok`.
#' @param pattern Passed to the backing `check_*()` function as `pattern`.
#' @param positive Passed to the backing `check_*()` function as `positive`.
#' @param sorted Passed to the backing `check_*()` function as `sorted`.
#' @param tol Passed to the backing `check_*()` function as `tol`.
#' @param typed.missing Passed to the backing `check_*()` function as `typed.missing`.
#' @param unique Passed to the backing `check_*()` function as `unique`.
#' @param upper Passed to the backing `check_*()` function as `upper`.
#' @param x Object to check.
#' @name checkmate_rlang
NULL

# chk_flag(): scalar, backed by check_flag()
#' @rdname checkmate_rlang
#' @export
chk_flag <- function(x, na.ok = FALSE, null.ok = FALSE, dim.ok = FALSE, class.ok = FALSE) {
  res <- check_flag(x, na.ok = na.ok, null.ok = null.ok)
  if (isTRUE(res) &&
      (dim.ok || is.null(attr(x, "dim", exact = TRUE))) &&
      (class.ok || !is.object(x)))
    return(invisible(x))
  chk_fail(x, res, dim.ok, class.ok)
}

# chk_logical(): vector, backed by check_logical()
#' @rdname checkmate_rlang
#' @export
chk_logical <- function(x, any.missing = TRUE, all.missing = TRUE, len = NULL, min.len = NULL, max.len = NULL, unique = FALSE, names = NULL, typed.missing = FALSE, null.ok = FALSE, dim.ok = FALSE, class.ok = FALSE) {
  res <- check_logical(x, any.missing = any.missing, all.missing = all.missing, len = len, min.len = min.len, max.len = max.len, unique = unique, names = names, typed.missing = typed.missing, null.ok = null.ok)
  if (isTRUE(res) &&
      (dim.ok || is.null(attr(x, "dim", exact = TRUE))) &&
      (class.ok || !is.object(x)))
    return(invisible(x))
  chk_fail(x, res, dim.ok, class.ok)
}

# chk_string(): scalar, backed by check_string()
#' @rdname checkmate_rlang
#' @export
chk_string <- function(x, na.ok = FALSE, n.chars = NULL, min.chars = NULL, max.chars = NULL, pattern = NULL, fixed = NULL, ignore.case = FALSE, null.ok = FALSE, dim.ok = FALSE, class.ok = FALSE) {
  res <- check_string(x, na.ok = na.ok, n.chars = n.chars, min.chars = min.chars, max.chars = max.chars, pattern = pattern, fixed = fixed, ignore.case = ignore.case, null.ok = null.ok)
  if (isTRUE(res) &&
      (dim.ok || is.null(attr(x, "dim", exact = TRUE))) &&
      (class.ok || !is.object(x)))
    return(invisible(x))
  chk_fail(x, res, dim.ok, class.ok)
}

# chk_character(): vector, backed by check_character()
#' @rdname checkmate_rlang
#' @export
chk_character <- function(x, n.chars = NULL, min.chars = NULL, max.chars = NULL, pattern = NULL, fixed = NULL, ignore.case = FALSE, any.missing = TRUE, all.missing = TRUE, len = NULL, min.len = NULL, max.len = NULL, unique = FALSE, sorted = FALSE, names = NULL, typed.missing = FALSE, null.ok = FALSE, dim.ok = FALSE, class.ok = FALSE) {
  res <- check_character(x, n.chars = n.chars, min.chars = min.chars, max.chars = max.chars, pattern = pattern, fixed = fixed, ignore.case = ignore.case, any.missing = any.missing, all.missing = all.missing, len = len, min.len = min.len, max.len = max.len, unique = unique, sorted = sorted, names = names, typed.missing = typed.missing, null.ok = null.ok)
  if (isTRUE(res) &&
      (dim.ok || is.null(attr(x, "dim", exact = TRUE))) &&
      (class.ok || !is.object(x)))
    return(invisible(x))
  chk_fail(x, res, dim.ok, class.ok)
}

# chk_number(): scalar, backed by check_number()
#' @rdname checkmate_rlang
#' @export
chk_number <- function(x, na.ok = FALSE, lower = -Inf, upper = Inf, finite = FALSE, null.ok = FALSE, dim.ok = FALSE, class.ok = FALSE) {
  res <- check_number(x, na.ok = na.ok, lower = lower, upper = upper, finite = finite, null.ok = null.ok)
  if (isTRUE(res) &&
      (dim.ok || is.null(attr(x, "dim", exact = TRUE))) &&
      (class.ok || !is.object(x)))
    return(invisible(x))
  chk_fail(x, res, dim.ok, class.ok)
}

# chk_numeric(): vector, backed by check_numeric()
#' @rdname checkmate_rlang
#' @export
chk_numeric <- function(x, lower = -Inf, upper = Inf, finite = FALSE, any.missing = TRUE, all.missing = TRUE, len = NULL, min.len = NULL, max.len = NULL, unique = FALSE, sorted = FALSE, names = NULL, typed.missing = FALSE, null.ok = FALSE, dim.ok = FALSE, class.ok = FALSE) {
  res <- check_numeric(x, lower = lower, upper = upper, finite = finite, any.missing = any.missing, all.missing = all.missing, len = len, min.len = min.len, max.len = max.len, unique = unique, sorted = sorted, names = names, typed.missing = typed.missing, null.ok = null.ok)
  if (isTRUE(res) &&
      (dim.ok || is.null(attr(x, "dim", exact = TRUE))) &&
      (class.ok || !is.object(x)))
    return(invisible(x))
  chk_fail(x, res, dim.ok, class.ok)
}

# chk_inumber(): scalar, backed by check_inumber()
#' @rdname checkmate_rlang
#' @export
chk_inumber <- function(x, na.ok = FALSE, lower = -Inf, upper = Inf, null.ok = FALSE, dim.ok = FALSE, class.ok = FALSE) {
  res <- check_inumber(x, na.ok = na.ok, lower = lower, upper = upper, null.ok = null.ok)
  if (isTRUE(res) &&
      (dim.ok || is.null(attr(x, "dim", exact = TRUE))) &&
      (class.ok || !is.object(x)))
    return(invisible(x))
  chk_fail(x, res, dim.ok, class.ok)
}

# chk_integer(): vector, backed by check_integer()
#' @rdname checkmate_rlang
#' @export
chk_integer <- function(x, lower = -Inf, upper = Inf, any.missing = TRUE, all.missing = TRUE, len = NULL, min.len = NULL, max.len = NULL, unique = FALSE, sorted = FALSE, names = NULL, typed.missing = FALSE, null.ok = FALSE, dim.ok = FALSE, class.ok = FALSE) {
  res <- check_integer(x, lower = lower, upper = upper, any.missing = any.missing, all.missing = all.missing, len = len, min.len = min.len, max.len = max.len, unique = unique, sorted = sorted, names = names, typed.missing = typed.missing, null.ok = null.ok)
  if (isTRUE(res) &&
      (dim.ok || is.null(attr(x, "dim", exact = TRUE))) &&
      (class.ok || !is.object(x)))
    return(invisible(x))
  chk_fail(x, res, dim.ok, class.ok)
}

# chk_dnumber(): scalar, backed by check_dnumber()
#' @rdname checkmate_rlang
#' @export
chk_dnumber <- function(x, na.ok = FALSE, lower = -Inf, upper = Inf, null.ok = FALSE, dim.ok = FALSE, class.ok = FALSE) {
  res <- check_dnumber(x, na.ok = na.ok, lower = lower, upper = upper, null.ok = null.ok)
  if (isTRUE(res) &&
      (dim.ok || is.null(attr(x, "dim", exact = TRUE))) &&
      (class.ok || !is.object(x)))
    return(invisible(x))
  chk_fail(x, res, dim.ok, class.ok)
}

# chk_double(): vector, backed by check_double()
#' @rdname checkmate_rlang
#' @export
chk_double <- function(x, lower = -Inf, upper = Inf, finite = FALSE, any.missing = TRUE, all.missing = TRUE, len = NULL, min.len = NULL, max.len = NULL, unique = FALSE, sorted = FALSE, names = NULL, typed.missing = FALSE, null.ok = FALSE, dim.ok = FALSE, class.ok = FALSE) {
  res <- check_double(x, lower = lower, upper = upper, finite = finite, any.missing = any.missing, all.missing = all.missing, len = len, min.len = min.len, max.len = max.len, unique = unique, sorted = sorted, names = names, typed.missing = typed.missing, null.ok = null.ok)
  if (isTRUE(res) &&
      (dim.ok || is.null(attr(x, "dim", exact = TRUE))) &&
      (class.ok || !is.object(x)))
    return(invisible(x))
  chk_fail(x, res, dim.ok, class.ok)
}

# chk_znumber(): scalar, backed by check_int()
#' @rdname checkmate_rlang
#' @export
chk_znumber <- function(x, na.ok = FALSE, lower = -Inf, upper = Inf, tol = sqrt(.Machine$double.eps), null.ok = FALSE, dim.ok = FALSE, class.ok = FALSE) {
  res <- check_int(x, na.ok = na.ok, lower = lower, upper = upper, tol = tol, null.ok = null.ok)
  if (isTRUE(res) &&
      (dim.ok || is.null(attr(x, "dim", exact = TRUE))) &&
      (class.ok || !is.object(x)))
    return(invisible(x))
  chk_fail(x, res, dim.ok, class.ok)
}

# chk_integerish(): vector, backed by check_integerish()
#' @rdname checkmate_rlang
#' @export
chk_integerish <- function(x, tol = sqrt(.Machine$double.eps), lower = -Inf, upper = Inf, any.missing = TRUE, all.missing = TRUE, len = NULL, min.len = NULL, max.len = NULL, unique = FALSE, sorted = FALSE, names = NULL, typed.missing = FALSE, null.ok = FALSE, dim.ok = FALSE, class.ok = FALSE) {
  res <- check_integerish(x, tol = tol, lower = lower, upper = upper, any.missing = any.missing, all.missing = all.missing, len = len, min.len = min.len, max.len = max.len, unique = unique, sorted = sorted, names = names, typed.missing = typed.missing, null.ok = null.ok)
  if (isTRUE(res) &&
      (dim.ok || is.null(attr(x, "dim", exact = TRUE))) &&
      (class.ok || !is.object(x)))
    return(invisible(x))
  chk_fail(x, res, dim.ok, class.ok)
}

# chk_count(): scalar, backed by check_count()
#' @rdname checkmate_rlang
#' @export
chk_count <- function(x, na.ok = FALSE, positive = FALSE, tol = sqrt(.Machine$double.eps), null.ok = FALSE, dim.ok = FALSE, class.ok = FALSE) {
  res <- check_count(x, na.ok = na.ok, positive = positive, tol = tol, null.ok = null.ok)
  if (isTRUE(res) &&
      (dim.ok || is.null(attr(x, "dim", exact = TRUE))) &&
      (class.ok || !is.object(x)))
    return(invisible(x))
  chk_fail(x, res, dim.ok, class.ok)
}

# chk_naturalish(): vector, backed by check_naturalish()
#' @rdname checkmate_rlang
#' @export
chk_naturalish <- function(x, tol = sqrt(.Machine$double.eps), upper = Inf, any.missing = TRUE, all.missing = TRUE, len = NULL, min.len = NULL, max.len = NULL, unique = FALSE, sorted = FALSE, names = NULL, null.ok = FALSE, dim.ok = FALSE, class.ok = FALSE) {
  res <- check_naturalish(x, tol = tol, upper = upper, any.missing = any.missing, all.missing = all.missing, len = len, min.len = min.len, max.len = max.len, unique = unique, sorted = sorted, names = names, null.ok = null.ok)
  if (isTRUE(res) &&
      (dim.ok || is.null(attr(x, "dim", exact = TRUE))) &&
      (class.ok || !is.object(x)))
    return(invisible(x))
  chk_fail(x, res, dim.ok, class.ok)
}

# chk_complex(): vector, backed by check_complex()
#' @rdname checkmate_rlang
#' @export
chk_complex <- function(x, any.missing = TRUE, all.missing = TRUE, len = NULL, min.len = NULL, max.len = NULL, unique = FALSE, names = NULL, typed.missing = FALSE, null.ok = FALSE, dim.ok = FALSE, class.ok = FALSE) {
  res <- check_complex(x, any.missing = any.missing, all.missing = all.missing, len = len, min.len = min.len, max.len = max.len, unique = unique, names = names, typed.missing = typed.missing, null.ok = null.ok)
  if (isTRUE(res) &&
      (dim.ok || is.null(attr(x, "dim", exact = TRUE))) &&
      (class.ok || !is.object(x)))
    return(invisible(x))
  chk_fail(x, res, dim.ok, class.ok)
}

# chk_raw(): vector, backed by check_raw()
#' @rdname checkmate_rlang
#' @export
chk_raw <- function(x, len = NULL, min.len = NULL, max.len = NULL, names = NULL, null.ok = FALSE, dim.ok = FALSE, class.ok = FALSE) {
  res <- check_raw(x, len = len, min.len = min.len, max.len = max.len, names = names, null.ok = null.ok)
  if (isTRUE(res) &&
      (dim.ok || is.null(attr(x, "dim", exact = TRUE))) &&
      (class.ok || !is.object(x)))
    return(invisible(x))
  chk_fail(x, res, dim.ok, class.ok)
}

# chk_scalar(): scalar, backed by check_scalar()
#' @rdname checkmate_rlang
#' @export
chk_scalar <- function(x, na.ok = FALSE, null.ok = FALSE, dim.ok = FALSE, class.ok = FALSE) {
  res <- check_scalar(x, na.ok = na.ok, null.ok = null.ok)
  if (isTRUE(res) &&
      (dim.ok || is.null(attr(x, "dim", exact = TRUE))) &&
      (class.ok || !is.object(x)))
    return(invisible(x))
  chk_fail(x, res, dim.ok, class.ok)
}

# chk_atomic(): vector, backed by check_atomic()
#' @rdname checkmate_rlang
#' @export
chk_atomic <- function(x, any.missing = TRUE, all.missing = TRUE, len = NULL, min.len = NULL, max.len = NULL, unique = FALSE, names = NULL, dim.ok = FALSE, class.ok = FALSE) {
  res <- check_atomic(x, any.missing = any.missing, all.missing = all.missing, len = len, min.len = min.len, max.len = max.len, unique = unique, names = names)
  if (isTRUE(res) &&
      (dim.ok || is.null(attr(x, "dim", exact = TRUE))) &&
      (class.ok || !is.object(x)))
    return(invisible(x))
  chk_fail(x, res, dim.ok, class.ok)
}

