# Generated by data-raw/generate-chk.R -- do not edit by hand.

#' @param x Object to check.
#' @param ... These dots are for future extensions and must be empty.
#' @param na.ok Are missing values permitted?
#' @param null.ok Is `NULL` permitted?
#' @param attr.ok Which attributes `x` may carry beyond those intrinsic to its type: a character vector of permitted attribute names, `FALSE` for none at all, or `TRUE` for any.
#' @param length Permitted length. `NULL` for any length, a scalar for one exact length, or a vector whose first and last elements give the minimum and the maximum.
#' @param range Permitted range of values, under the same first/last rule as `length`. For the character types it constrains `nchar()` of the elements instead, and for the date and time types the bounds are themselves `Date` or `POSIXct`.
#' @rdname checkmate_rlang
#' @name checkmate_rlang
NULL

# chk_flag(): scalar, backed by check_flag()

#' @rdname checkmate_rlang
#' @export
chk_flag <- function(x, ..., na.ok = FALSE, null.ok = FALSE, attr.ok = "names") {

  # No arguments, return on fastest path
  if (nargs() == 1L && isTRUE(check_flag(x)) && (is.vector(x, "any")) )
      return(invisible(x))

  # Anything in the dots is a typo, not an extension
  chk_dots_empty()

  # More detailed translation of arguments to check_*() equivalents

  res <- check_flag(x,
                    na.ok = na.ok,
                    null.ok = null.ok)
  if (isTRUE(res) && attrs_ok(x, attr.ok)) return(invisible(x))
  chk_fail(x, res, attr.ok)
}
# chk_logical(): vector, backed by check_logical()
# pinned: all.missing = TRUE, unique = FALSE, names = NULL, typed.missing =
#   FALSE
#' @rdname checkmate_rlang
#' @export
chk_logical <- function(x, ..., na.ok = TRUE, null.ok = FALSE, attr.ok = "names", length = NULL) {

  # No arguments, return on fastest path
  if (nargs() == 1L && isTRUE(check_logical(x)) && (is.vector(x, "any")) )
      return(invisible(x))

  # Anything in the dots is a typo, not an extension
  chk_dots_empty()

  # More detailed translation of arguments to check_*() equivalents
  len <- lo_hi(length)
  res <- check_logical(x,
                       any.missing = na.ok,
                       null.ok = null.ok,
                       len = exact(length),
                       min.len = len[1L],
                       max.len = len[2L])
  if (isTRUE(res) && attrs_ok(x, attr.ok)) return(invisible(x))
  chk_fail(x, res, attr.ok)
}
# chk_string(): scalar, backed by check_string()
# pinned: pattern = NULL, fixed = NULL, ignore.case = FALSE
#' @rdname checkmate_rlang
#' @export
chk_string <- function(x, ..., na.ok = FALSE, null.ok = FALSE, attr.ok = "names", range = NULL) {

  # No arguments, return on fastest path
  if (nargs() == 1L && isTRUE(check_string(x)) && (is.vector(x, "any")) )
      return(invisible(x))

  # Anything in the dots is a typo, not an extension
  chk_dots_empty()

  # More detailed translation of arguments to check_*() equivalents
  rng <- lo_hi(range)
  res <- check_string(x,
                      na.ok = na.ok,
                      null.ok = null.ok,
                      n.chars = exact(range),
                      min.chars = rng[1L],
                      max.chars = rng[2L])
  if (isTRUE(res) && attrs_ok(x, attr.ok)) return(invisible(x))
  chk_fail(x, res, attr.ok)
}
# chk_character(): vector, backed by check_character()
# pinned: pattern = NULL, fixed = NULL, ignore.case = FALSE, all.missing =
#   TRUE, unique = FALSE, sorted = FALSE, names = NULL, typed.missing = FALSE
#' @rdname checkmate_rlang
#' @export
chk_character <- function(x, ..., na.ok = TRUE, null.ok = FALSE, attr.ok = "names", length = NULL, range = NULL) {

  # No arguments, return on fastest path
  if (nargs() == 1L && isTRUE(check_character(x)) && (is.vector(x, "any")) )
      return(invisible(x))

  # Anything in the dots is a typo, not an extension
  chk_dots_empty()

  # More detailed translation of arguments to check_*() equivalents
  len <- lo_hi(length)
  rng <- lo_hi(range)
  res <- check_character(x,
                         any.missing = na.ok,
                         null.ok = null.ok,
                         len = exact(length),
                         min.len = len[1L],
                         max.len = len[2L],
                         n.chars = exact(range),
                         min.chars = rng[1L],
                         max.chars = rng[2L])
  if (isTRUE(res) && attrs_ok(x, attr.ok)) return(invisible(x))
  chk_fail(x, res, attr.ok)
}
# chk_number(): scalar, backed by check_number()
# pinned: finite = FALSE
#' @rdname checkmate_rlang
#' @export
chk_number <- function(x, ..., na.ok = FALSE, null.ok = FALSE, attr.ok = "names", range = NULL) {

  # No arguments, return on fastest path
  if (nargs() == 1L && isTRUE(check_number(x)) && (is.vector(x, "any")) )
      return(invisible(x))

  # Anything in the dots is a typo, not an extension
  chk_dots_empty()

  # More detailed translation of arguments to check_*() equivalents
  rng <- lo_hi(range, c(-Inf, Inf))
  res <- check_number(x,
                      na.ok = na.ok,
                      null.ok = null.ok,
                      lower = rng[1L],
                      upper = rng[2L])
  if (isTRUE(res) && attrs_ok(x, attr.ok)) return(invisible(x))
  chk_fail(x, res, attr.ok)
}
# chk_numeric(): vector, backed by check_numeric()
# pinned: finite = FALSE, all.missing = TRUE, unique = FALSE, sorted = FALSE,
#   names = NULL, typed.missing = FALSE
#' @rdname checkmate_rlang
#' @export
chk_numeric <- function(x, ..., na.ok = TRUE, null.ok = FALSE, attr.ok = "names", length = NULL, range = NULL) {

  # No arguments, return on fastest path
  if (nargs() == 1L && isTRUE(check_numeric(x)) && (is.vector(x, "any")) )
      return(invisible(x))

  # Anything in the dots is a typo, not an extension
  chk_dots_empty()

  # More detailed translation of arguments to check_*() equivalents
  len <- lo_hi(length)
  rng <- lo_hi(range, c(-Inf, Inf))
  res <- check_numeric(x,
                       any.missing = na.ok,
                       null.ok = null.ok,
                       len = exact(length),
                       min.len = len[1L],
                       max.len = len[2L],
                       lower = rng[1L],
                       upper = rng[2L])
  if (isTRUE(res) && attrs_ok(x, attr.ok)) return(invisible(x))
  chk_fail(x, res, attr.ok)
}
# chk_inumber(): scalar, backed by check_inumber()

#' @rdname checkmate_rlang
#' @export
chk_inumber <- function(x, ..., na.ok = FALSE, null.ok = FALSE, attr.ok = "names", range = NULL) {

  # No arguments, return on fastest path
  if (nargs() == 1L && isTRUE(check_inumber(x)) && (is.vector(x, "any")) )
      return(invisible(x))

  # Anything in the dots is a typo, not an extension
  chk_dots_empty()

  # More detailed translation of arguments to check_*() equivalents
  rng <- lo_hi(range, c(-Inf, Inf))
  res <- check_inumber(x,
                       na.ok = na.ok,
                       null.ok = null.ok,
                       lower = rng[1L],
                       upper = rng[2L])
  if (isTRUE(res) && attrs_ok(x, attr.ok)) return(invisible(x))
  chk_fail(x, res, attr.ok)
}
# chk_integer(): vector, backed by check_integer()
# pinned: all.missing = TRUE, unique = FALSE, sorted = FALSE, names = NULL,
#   typed.missing = FALSE
#' @rdname checkmate_rlang
#' @export
chk_integer <- function(x, ..., na.ok = TRUE, null.ok = FALSE, attr.ok = "names", length = NULL, range = NULL) {

  # No arguments, return on fastest path
  if (nargs() == 1L && isTRUE(check_integer(x)) && (is.vector(x, "any")) )
      return(invisible(x))

  # Anything in the dots is a typo, not an extension
  chk_dots_empty()

  # More detailed translation of arguments to check_*() equivalents
  len <- lo_hi(length)
  rng <- lo_hi(range, c(-Inf, Inf))
  res <- check_integer(x,
                       any.missing = na.ok,
                       null.ok = null.ok,
                       len = exact(length),
                       min.len = len[1L],
                       max.len = len[2L],
                       lower = rng[1L],
                       upper = rng[2L])
  if (isTRUE(res) && attrs_ok(x, attr.ok)) return(invisible(x))
  chk_fail(x, res, attr.ok)
}
# chk_dnumber(): scalar, backed by check_dnumber()

#' @rdname checkmate_rlang
#' @export
chk_dnumber <- function(x, ..., na.ok = FALSE, null.ok = FALSE, attr.ok = "names", range = NULL) {

  # No arguments, return on fastest path
  if (nargs() == 1L && isTRUE(check_dnumber(x)) && (is.vector(x, "any")) )
      return(invisible(x))

  # Anything in the dots is a typo, not an extension
  chk_dots_empty()

  # More detailed translation of arguments to check_*() equivalents
  rng <- lo_hi(range, c(-Inf, Inf))
  res <- check_dnumber(x,
                       na.ok = na.ok,
                       null.ok = null.ok,
                       lower = rng[1L],
                       upper = rng[2L])
  if (isTRUE(res) && attrs_ok(x, attr.ok)) return(invisible(x))
  chk_fail(x, res, attr.ok)
}
# chk_double(): vector, backed by check_double()
# pinned: finite = FALSE, all.missing = TRUE, unique = FALSE, sorted = FALSE,
#   names = NULL, typed.missing = FALSE
#' @rdname checkmate_rlang
#' @export
chk_double <- function(x, ..., na.ok = TRUE, null.ok = FALSE, attr.ok = "names", length = NULL, range = NULL) {

  # No arguments, return on fastest path
  if (nargs() == 1L && isTRUE(check_double(x)) && (is.vector(x, "any")) )
      return(invisible(x))

  # Anything in the dots is a typo, not an extension
  chk_dots_empty()

  # More detailed translation of arguments to check_*() equivalents
  len <- lo_hi(length)
  rng <- lo_hi(range, c(-Inf, Inf))
  res <- check_double(x,
                      any.missing = na.ok,
                      null.ok = null.ok,
                      len = exact(length),
                      min.len = len[1L],
                      max.len = len[2L],
                      lower = rng[1L],
                      upper = rng[2L])
  if (isTRUE(res) && attrs_ok(x, attr.ok)) return(invisible(x))
  chk_fail(x, res, attr.ok)
}
# chk_znumber(): scalar, backed by check_int()
# pinned: tol = sqrt(.Machine$double.eps)
#' @rdname checkmate_rlang
#' @export
chk_znumber <- function(x, ..., na.ok = FALSE, null.ok = FALSE, attr.ok = "names", range = NULL) {

  # No arguments, return on fastest path
  if (nargs() == 1L && isTRUE(check_int(x)) && (is.vector(x, "any")) )
      return(invisible(x))

  # Anything in the dots is a typo, not an extension
  chk_dots_empty()

  # More detailed translation of arguments to check_*() equivalents
  rng <- lo_hi(range, c(-Inf, Inf))
  res <- check_int(x,
                   na.ok = na.ok,
                   null.ok = null.ok,
                   lower = rng[1L],
                   upper = rng[2L])
  if (isTRUE(res) && attrs_ok(x, attr.ok)) return(invisible(x))
  chk_fail(x, res, attr.ok)
}
# chk_integerish(): vector, backed by check_integerish()
# pinned: tol = sqrt(.Machine$double.eps), all.missing = TRUE, unique =
#   FALSE, sorted = FALSE, names = NULL, typed.missing = FALSE
#' @rdname checkmate_rlang
#' @export
chk_integerish <- function(x, ..., na.ok = TRUE, null.ok = FALSE, attr.ok = "names", length = NULL, range = NULL) {

  # No arguments, return on fastest path
  if (nargs() == 1L && isTRUE(check_integerish(x)) && (is.vector(x, "any")) )
      return(invisible(x))

  # Anything in the dots is a typo, not an extension
  chk_dots_empty()

  # More detailed translation of arguments to check_*() equivalents
  len <- lo_hi(length)
  rng <- lo_hi(range, c(-Inf, Inf))
  res <- check_integerish(x,
                          any.missing = na.ok,
                          null.ok = null.ok,
                          len = exact(length),
                          min.len = len[1L],
                          max.len = len[2L],
                          lower = rng[1L],
                          upper = rng[2L])
  if (isTRUE(res) && attrs_ok(x, attr.ok)) return(invisible(x))
  chk_fail(x, res, attr.ok)
}
# chk_count(): scalar, backed by check_count()
# pinned: positive = FALSE, tol = sqrt(.Machine$double.eps)
#' @rdname checkmate_rlang
#' @export
chk_count <- function(x, ..., na.ok = FALSE, null.ok = FALSE, attr.ok = "names") {

  # No arguments, return on fastest path
  if (nargs() == 1L && isTRUE(check_count(x)) && (is.vector(x, "any")) )
      return(invisible(x))

  # Anything in the dots is a typo, not an extension
  chk_dots_empty()

  # More detailed translation of arguments to check_*() equivalents

  res <- check_count(x,
                     na.ok = na.ok,
                     null.ok = null.ok)
  if (isTRUE(res) && attrs_ok(x, attr.ok)) return(invisible(x))
  chk_fail(x, res, attr.ok)
}
# chk_naturalish(): vector, backed by check_naturalish()
# pinned: tol = sqrt(.Machine$double.eps), all.missing = TRUE, unique =
#   FALSE, sorted = FALSE, names = NULL
#' @rdname checkmate_rlang
#' @export
chk_naturalish <- function(x, ..., na.ok = TRUE, null.ok = FALSE, attr.ok = "names", length = NULL, range = NULL) {

  # No arguments, return on fastest path
  if (nargs() == 1L && isTRUE(check_naturalish(x)) && (is.vector(x, "any")) )
      return(invisible(x))

  # Anything in the dots is a typo, not an extension
  chk_dots_empty()

  # More detailed translation of arguments to check_*() equivalents
  len <- lo_hi(length)
  rng <- lo_hi(range, c(0, Inf))
  res <- check_naturalish(x,
                          any.missing = na.ok,
                          null.ok = null.ok,
                          len = exact(length),
                          min.len = len[1L],
                          max.len = len[2L],
                          lower = rng[1L],
                          upper = rng[2L])
  if (isTRUE(res) && attrs_ok(x, attr.ok)) return(invisible(x))
  chk_fail(x, res, attr.ok)
}
# chk_factor(): vector, backed by check_factor()
# pinned: levels = NULL, ordered = NA, empty.levels.ok = TRUE, all.missing =
#   TRUE, n.levels = NULL, min.levels = NULL, max.levels = NULL, unique =
#   FALSE, names = NULL
#' @rdname checkmate_rlang
#' @export
chk_factor <- function(x, ..., na.ok = TRUE, null.ok = FALSE, attr.ok = "names", length = NULL) {

  # No arguments, return on fastest path
  if (nargs() == 1L && isTRUE(check_factor(x)) && (attrs_ok(x, "names", c("class", "levels"))) )
      return(invisible(x))

  # Anything in the dots is a typo, not an extension
  chk_dots_empty()

  # More detailed translation of arguments to check_*() equivalents
  len <- lo_hi(length)
  res <- check_factor(x,
                      any.missing = na.ok,
                      null.ok = null.ok,
                      len = exact(length),
                      min.len = len[1L],
                      max.len = len[2L])
  if (isTRUE(res) && attrs_ok(x, attr.ok, c("class", "levels"))) return(invisible(x))
  chk_fail(x, res, attr.ok, c("class", "levels"))
}
# chk_complex(): vector, backed by check_complex()
# pinned: all.missing = TRUE, unique = FALSE, names = NULL, typed.missing =
#   FALSE
#' @rdname checkmate_rlang
#' @export
chk_complex <- function(x, ..., na.ok = TRUE, null.ok = FALSE, attr.ok = "names", length = NULL) {

  # No arguments, return on fastest path
  if (nargs() == 1L && isTRUE(check_complex(x)) && (is.vector(x, "any")) )
      return(invisible(x))

  # Anything in the dots is a typo, not an extension
  chk_dots_empty()

  # More detailed translation of arguments to check_*() equivalents
  len <- lo_hi(length)
  res <- check_complex(x,
                       any.missing = na.ok,
                       null.ok = null.ok,
                       len = exact(length),
                       min.len = len[1L],
                       max.len = len[2L])
  if (isTRUE(res) && attrs_ok(x, attr.ok)) return(invisible(x))
  chk_fail(x, res, attr.ok)
}
# chk_raw(): vector, backed by check_raw()
# pinned: names = NULL
#' @rdname checkmate_rlang
#' @export
chk_raw <- function(x, ..., null.ok = FALSE, attr.ok = "names", length = NULL) {

  # No arguments, return on fastest path
  if (nargs() == 1L && isTRUE(check_raw(x)) && (is.vector(x, "any")) )
      return(invisible(x))

  # Anything in the dots is a typo, not an extension
  chk_dots_empty()

  # More detailed translation of arguments to check_*() equivalents
  len <- lo_hi(length)
  res <- check_raw(x,
                   null.ok = null.ok,
                   len = exact(length),
                   min.len = len[1L],
                   max.len = len[2L])
  if (isTRUE(res) && attrs_ok(x, attr.ok)) return(invisible(x))
  chk_fail(x, res, attr.ok)
}
# chk_day(): scalar, backed by check_day()

#' @rdname checkmate_rlang
#' @export
chk_day <- function(x, ..., na.ok = FALSE, null.ok = FALSE, attr.ok = "names", range = NULL) {

  # No arguments, return on fastest path
  if (nargs() == 1L && isTRUE(check_day(x)) && (attrs_ok(x, "names", "class")) )
      return(invisible(x))

  # Anything in the dots is a typo, not an extension
  chk_dots_empty()

  # More detailed translation of arguments to check_*() equivalents
  rng <- lo_hi(range, NULL)
  res <- check_day(x,
                   na.ok = na.ok,
                   null.ok = null.ok,
                   lower = rng[1L],
                   upper = rng[2L])
  if (isTRUE(res) && attrs_ok(x, attr.ok, "class")) return(invisible(x))
  chk_fail(x, res, attr.ok, "class")
}
# chk_date(): vector, backed by check_date()
# pinned: all.missing = TRUE, unique = FALSE
#' @rdname checkmate_rlang
#' @export
chk_date <- function(x, ..., na.ok = TRUE, null.ok = FALSE, attr.ok = "names", length = NULL, range = NULL) {

  # No arguments, return on fastest path
  if (nargs() == 1L && isTRUE(check_date(x)) && (attrs_ok(x, "names", "class")) )
      return(invisible(x))

  # Anything in the dots is a typo, not an extension
  chk_dots_empty()

  # More detailed translation of arguments to check_*() equivalents
  len <- lo_hi(length)
  rng <- lo_hi(range, NULL)
  res <- check_date(x,
                    any.missing = na.ok,
                    null.ok = null.ok,
                    len = exact(length),
                    min.len = len[1L],
                    max.len = len[2L],
                    lower = rng[1L],
                    upper = rng[2L])
  if (isTRUE(res) && attrs_ok(x, attr.ok, "class")) return(invisible(x))
  chk_fail(x, res, attr.ok, "class")
}
# chk_instant(): scalar, backed by check_instant()

#' @rdname checkmate_rlang
#' @export
chk_instant <- function(x, ..., na.ok = FALSE, null.ok = FALSE, attr.ok = "names", range = NULL) {

  # No arguments, return on fastest path
  if (nargs() == 1L && isTRUE(check_instant(x)) && (attrs_ok(x, "names", c("class", "tzone"))) )
      return(invisible(x))

  # Anything in the dots is a typo, not an extension
  chk_dots_empty()

  # More detailed translation of arguments to check_*() equivalents
  rng <- lo_hi(range, NULL)
  res <- check_instant(x,
                       na.ok = na.ok,
                       null.ok = null.ok,
                       lower = rng[1L],
                       upper = rng[2L])
  if (isTRUE(res) && attrs_ok(x, attr.ok, c("class", "tzone"))) return(invisible(x))
  chk_fail(x, res, attr.ok, c("class", "tzone"))
}
# chk_posixct(): vector, backed by check_posixct()
# pinned: all.missing = TRUE, unique = FALSE, sorted = FALSE
#' @rdname checkmate_rlang
#' @export
chk_posixct <- function(x, ..., na.ok = TRUE, null.ok = FALSE, attr.ok = "names", length = NULL, range = NULL) {

  # No arguments, return on fastest path
  if (nargs() == 1L && isTRUE(check_posixct(x)) && (attrs_ok(x, "names", c("class", "tzone"))) )
      return(invisible(x))

  # Anything in the dots is a typo, not an extension
  chk_dots_empty()

  # More detailed translation of arguments to check_*() equivalents
  len <- lo_hi(length)
  rng <- lo_hi(range, NULL)
  res <- check_posixct(x,
                       any.missing = na.ok,
                       null.ok = null.ok,
                       len = exact(length),
                       min.len = len[1L],
                       max.len = len[2L],
                       lower = rng[1L],
                       upper = rng[2L])
  if (isTRUE(res) && attrs_ok(x, attr.ok, c("class", "tzone"))) return(invisible(x))
  chk_fail(x, res, attr.ok, c("class", "tzone"))
}
# chk_scalar(): scalar, backed by check_scalar()

#' @rdname checkmate_rlang
#' @export
chk_scalar <- function(x, ..., na.ok = FALSE, null.ok = FALSE, attr.ok = "names") {

  # No arguments, return on fastest path
  if (nargs() == 1L && isTRUE(check_scalar(x)) && (is.vector(x, "any")) )
      return(invisible(x))

  # Anything in the dots is a typo, not an extension
  chk_dots_empty()

  # More detailed translation of arguments to check_*() equivalents

  res <- check_scalar(x,
                      na.ok = na.ok,
                      null.ok = null.ok)
  if (isTRUE(res) && attrs_ok(x, attr.ok)) return(invisible(x))
  chk_fail(x, res, attr.ok)
}
# chk_atomic(): vector, backed by check_atomic()
# pinned: all.missing = TRUE, unique = FALSE, names = NULL
#' @rdname checkmate_rlang
#' @export
chk_atomic <- function(x, ..., na.ok = TRUE, attr.ok = "names", length = NULL) {

  # No arguments, return on fastest path
  if (nargs() == 1L && isTRUE(check_atomic(x)) && (is.vector(x, "any")) )
      return(invisible(x))

  # Anything in the dots is a typo, not an extension
  chk_dots_empty()

  # More detailed translation of arguments to check_*() equivalents
  len <- lo_hi(length)
  res <- check_atomic(x,
                      any.missing = na.ok,
                      len = exact(length),
                      min.len = len[1L],
                      max.len = len[2L])
  if (isTRUE(res) && attrs_ok(x, attr.ok)) return(invisible(x))
  chk_fail(x, res, attr.ok)
}
